### ISSUE TITLE
Support Elastic Search images from elastic.io docker registry.

### ISSUE THREAD

**Issue by ktamayop** [d3sw/mold#115]
When running mold on any project that's using elastic search for integration testing we're seeing the builds fail. The error message indicates that the elastic search service container created is not routeable from the api container running the integration tests. In this case a dotnet core 2.0 API (but the same error has occurred on a Golang 1.9 API too).

**Context:** 
1. The images for elastic search supported by docker have been deprecated and according to [docker store site](https://store.docker.com/images/elasticsearch) these images are no going to be updated anymore after elastic version 6.0.0 has been released.
2. The services we're currently developing should be using elastic search 5.6.2 to match the clustered version - `consul-elasticsearch` - we're using on test environments. 
3. When using `elasticsearch:5.x-alpine` (now deprecated) image, on our build, it works properly.
4. When trying to use one of the newer images - from elastic.io/* - registry (e.g: docker.elastic.co/elasticsearch/elasticsearch:5.6.2) and because the created elastic service container is not staying up during the build, when the integration tests are run, the elastic database cannot be found and tests fail.
5. Running mold locally it works properly, but fails on CI server. So this could be a docker issue also.

**Environment:**
**Mold version:** 0.2.8 commit=v0_2_8/ddff214 buildtime=2017-12-27T18:03:27-0800.
**OS:** Windows 10 Pro. 1709.

The following excerpt belongs to the `.mold.yaml` file from **[transformer project](https://github.com/d3sw/transformer)**. Using the legacy alpine image, the build completes successfully:

```yaml
# Start up elastic search
services:
  - image: elasticsearch:5.6-alpine
    name: elasticsearch.transformer
```
However when changing the elastic image to use the newer versions, the build fails because the elastic db container cannot be found during integration tests run:

```yaml
# Start up elastic search
services:
  - image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    name: elasticsearch.transformer
```

We should support the newer versions of elastic search images (from **elastic.io** registry) on mold builds.
