### ISSUE TITLE
Do not allow artifacts without a name.

### ISSUE THREAD

**Issue by euforia** [d3sw/mold#39]
Artifacts can be produced with out names by simply omitting the name field.  

Mold should validate the whole config before starting any of the build processes.

To reproduce:

```
...
artifiacts:
  - name: foobar
  - docker: Dockerfile
```

This will build 2 artifacts with the second one containing a blank name.
