### ISSUE TITLE
Add documentation for using context in the artifacts section

### ISSUE THREAD

**Issue by toddschilling** [d3sw/mold#73]
I've found that it's easier to use the context property when you're building an entire image from a subfolder.  This way your `Dockerfile` paths remain relative to the location of the `Dockerfile` and not the `mold.yml` file.

```
artifacts:
  images:
    - name: subapp
      context: subappfolder
```
