### ISSUE TITLE
Defining multiple builds will cause only they last build to log to STDOUT

### ISSUE THREAD

**Issue by toddschilling** [d3sw/mold#76]
The following build configuration will cause mold to only generate output for the node build.

```
mold --version
0.2.5 commit=master/d10abb2 buildtime=2017-04-25T12:53:38-0700
```

```
build:
  - image: microsoft/dotnet:2.0-sdk
    workdir: /
    commands:
      - dotnet restore myservice.csproj 
  - image: node:8.6-alpine
    workdir: /
    commands:
      - npm install
```
