### ISSUE TITLE
Allow image name overriding for container

### ISSUE THREAD

**Issue by pavelvasilenka** [d3sw/mold#79]
I try to run several instances of one image.
I need it to replicate clustering behavior of RethinkDB.

Example config:
```
  - image: "docketbook/rethinkdb-cluster:latest"
    environment:
    - CONSUL_ADDRESS=127.0.0.1
    - CONSUL_ENVIRONMENT=app
    - SERVICE_NAME=app
  - image: "docketbook/rethinkdb-cluster:latest"
    environment:
    - CONSUL_ADDRESS=127.0.0.1
    - CONSUL_ENVIRONMENT=app
    - SERVICE_NAME=app
```
Here is an error i get:
```
2017/10/12 18:33:09 Error response from daemon: Conflict. The container name "/rethinkdb-cluster.app" is already in use by container "cbbb58a1b78d2074eacb9b42f607c97c8065239971cc149b672b6a91f6dd0415". You have to remove (or rename) that container to be able to reuse that name.
```
